services:

  nginx:
    image: nginx:latest
    container_name: nginx
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf
    ports:
      - 8181:81
    depends_on:
      - node 
      - frontend

  node:
    build: 
      context: ./backend
    container_name: backend
    volumes:
      - ./backend:/usr/src/app
    ports:
      - 3000:3000 

  frontend:
    build: 
      context: ./frontend
    container_name: frontend
    volumes:
      - ./frontend:/usr/src/app
    ports:
      - 5173:5173
